// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment

To test that the deployment has been successful, perform the following steps:

1.	Establish an RDP connection to both StarWind VSAN EC2 Storage instances and Witness instance.
2.	On StarWind VSAN EC2 Storage and Witness instances, open StarWind Management Console, and connect the instances using their management IP addresses or DNS names. 
3.	Verify that StarWind HA device is synchronized on both Storage instances and on the Witness instance, its mode is set to Witness. 
4.	Verify that the Health Status of StarWind HA device displays “Storage is working properly” on all three instances. 
5.	On both StarWind VSAN EC2 Storage instances, navigate to Disk Management and verify that the CSV disk is present and healthy. 


== Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading

After the deployment, the following steps should be performed:

1. Deploy the Failover Cluster, set the required name and a static IP address for it. To create a Failover Cluster, please refer to the StarWind VSAN technical guide "Creating a Failover Cluster in Windows Server" section: https://www.starwindsoftware.com/resource-library/starwind-virtual-san-for-hyper-v-2-node-hyperconverged-scenario-with-windows-server-2016/#14bdf4cea7ba8ca523dcfb621c1969fa624feec3  
2. Add StarWind HA device to cluster. In Failover Cluster Manager, navigate to Cluster -> Storage -> Disks. Click Add Disk in the Actions panel, choose StarWind disks from the list and confirm the selection.
3. If it is required to use StarWind HA device as a cluster shared volume (CSV), right-click the disk and select Add to Cluster Shared Volumes.
4. Setup the Failover Cluster quorum. Create an SMB file share on the StarWind VSAN EC2 Witness instance that will host the file share witness for the Failover Cluster.
5. After this, configure file share witness. For this, right-click the cluster node, navigate to More Actions -> Configure Cluster Quorum Settings and click Next. 
6. Select the quorum witness and click next.
7. Select All Nodes (both StarWind VSAN EC2 Storage instances) and click Next.
8. Select Configure a file share witness and click Next.
9. Type the share path in the File Share Path field and click Next.
10. Check the summary page and click Finish to complete the quorum settings


== Post-deployment testing
// If steps are required to test the deployment, add them here. If not, remove the heading
The following tests can be performed to validate the Failover Cluster proper operation:

1. In case StarWind HA device is used as a cluster shared volume (CSV), create a test VM (can be created without OS), place it on StarWind HA CSV and make sure the VM is able to live migrate. 
2. Shut down one of the StarWind VSAN EC2 Storage instances and make sure that a test VM or role is able to failover to a partner instance. To perform this, follow the steps described in the following article: https://knowledgebase.starwindsoftware.com/maintenance/how-to-restartshutdown-servers-with-starwind-vsan-installed/ 

Make sure that the tests above are successful for both StarWind VSAN EC2 Storage instances.   

Once the tests above have passed succesfully, you can deploy a required VM or role and proceed with workload testing. This can include live migration, failover and general operation and performance tests.

== Best practices for using StarWind VSAN on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.


With limited control access to the hardware in cloud environments, it is recommended to create StarWind HA devices with Node Majority failover strategy which eliminates the risk of Split Brain in case of network connectivity loss between StarWind VSAN EC2 Storage instances and allows withstanding a StarWind VSAN EC2 instance failure: https://www.starwindsoftware.com/resource-library/starwind-witness-node/   

== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

It is recommended not to backup the StarWind EC2 instances themselves but only data or workloads running on top of them. In case it is required to backup a StarWind VSAN EC2 instance, maintenance mode must be enabled: https://www.starwindsoftware.com/help/MaintenanceMode.html

For additional information on backups, please refer to StarWind VSAN Backup Best Practices: https://www.starwindsoftware.com/best-practices/starwind-virtual-san-backup-best-practices/   

== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

It is also possible to connect other EC2 instances to use the StarWind HA storage. For this, please add a dedicated network interface for storage discovery via iSCSI on each additional EC2 instance and use it to connect storage from StarWind VSAN EC2 Storage instances.      
