//Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps leave this file empty.

== Test the deployment

To test that the deployment has been successful, perform the following steps:

1.	Establish an RDP connection to both StarWind VSAN EC2 Storage instances and Witness instance.
2.	On StarWind VSAN EC2 Storage and Witness instances, open StarWind Management Console, and connect the instances using their management IP addresses or DNS names. 
3.	Verify that StarWind HA device is synchronized on both Storage instances and on the Witness instance, its mode is set to Witness. 
4.	Verify that the Health Status of StarWind HA device displays “Storage is working properly” on all three instances. 
5.	On both StarWind VSAN EC2 Storage instances, navigate to Disk Management and verify that the CSV disk is present and healthy. 

== Postdeployment steps

=== Configure Windows Server Failover Cluster

1. Deploy the Failover Cluster, set the required name and static IP addresses for it. Add any additional IP addresses needed for the cluster and its resources as secondary private IP addresses on the management network interface of the StarWind VSAN EC2 Storage instances. To create a Failover Cluster, please refer to https://www.starwindsoftware.com/resource-library/starwind-virtual-san-for-hyper-v-2-node-hyperconverged-scenario-with-windows-server-2016/#14bdf4cea7ba8ca523dcfb621c1969fa624feec3[Creating a Failover Cluster in Windows Server] in the StarWind VSAN technical guide.
2. Add StarWind HA device to cluster. In Failover Cluster Manager, navigate to Cluster -> Storage -> Disks. Click Add Disk in the Actions panel, choose StarWind disks from the list and confirm the selection.
3. If it is required to use StarWind HA device as a cluster shared volume (CSV), right-click the disk and select Add to Cluster Shared Volumes.
4. Setup the Failover Cluster quorum. Create an SMB file share on the StarWind VSAN EC2 Witness instance that will host the file share witness for the Failover Cluster.
5. After this, configure file share witness. For this, right-click the cluster node, navigate to More Actions -> Configure Cluster Quorum Settings and click Next.
6. Select the quorum witness and click next.
7. Select All Nodes (both StarWind VSAN EC2 Storage instances) and click Next.
8. Select Configure a file share witness and click Next.
9. Type the share path in the File Share Path field and click Next.
10. Check the summary page and click Finish to complete the quorum settings
