== Failover Cluster simple testing
// If steps are required to test the deployment, add them here. If not, remove the heading
The following tests can be performed to confirm that the Failover Cluster is operating properly:

1. In case StarWind HA device is used as a cluster shared volume (CSV), create a test VM (can be created without OS), place it on StarWind HA CSV and make sure the VM is able to live migrate. 
2. Shut down one of the StarWind VSAN EC2 Storage instances and make sure that a test VM or role is able to failover to a partner instance. To perform this, follow the steps described in https://knowledgebase.starwindsoftware.com/maintenance/how-to-restartshutdown-servers-with-starwind-vsan-installed/[How to restart/shutdown servers with StarWind VSAN installed].

Make sure that the tests above are successful for both StarWind VSAN EC2 Storage instances.   

Once the tests above have passed successfully, you can deploy your required application, role or VM and proceed with workload testing. This can include live migration, failover and general operation and performance tests.

== Best practices for using StarWind VSAN on AWS
// Provide postdeployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

With limited control access to the hardware in cloud environments, it is recommended to create StarWind HA devices with Node Majority failover strategy which eliminates the risk of Split Brain in case of network connectivity loss between StarWind VSAN EC2 Storage instances and allows withstanding a StarWind VSAN EC2 instance failure. This QuickStart follows this best practice. For more information, see https://www.starwindsoftware.com/resource-library/starwind-witness-node/[StarWind Witness].

== Security
// Provide postdeployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

It is recommended not to backup the StarWind EC2 instances themselves but only data or workloads running on top of them. In case it is required to backup a StarWind VSAN EC2 instance, https://www.starwindsoftware.com/help/MaintenanceMode.html[maintenance mode] must be enabled.

For additional information on backups, please refer to https://www.starwindsoftware.com/best-practices/starwind-virtual-san-backup-best-practices/[StarWind VSAN Backup Best Practices].

== (Optional) Connect other EC2 instances to the StarWind HA storage
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

To connect other EC2 instances to the StarWind HA storage, add a separate network interface for storage discovery using iSCSI on each additional EC2 instance. Use this network interface to connect storage from StarWind VSAN EC2 storage instances. Direct each storage connection—whether it originates from a separate iSCSI network interface or the default network interface—toward the StarWind VSAN EC2 storage instances' iSCSI network interface. You can identify the correct network interface from its description in the AWS Console.